import {
    UserOutlined,
    HomeOutlined,
    AlignRightOutlined,
    UnlockOutlined,
    WalletOutlined,
} from '@ant-design/icons';
const menu = [
    {
        title:'首页',
        path:"/home",
        icon:HomeOutlined
    },
    {
        title:'用户管理',
        icon:UserOutlined,
        path:'/user-manage',
        children:[
            {
                title:'用户列表',
                path:'/user-manage/user',
                icon:AlignRightOutlined
            }
        ]
    },
    {
        title:'权限管理',
        icon:UnlockOutlined,
        path:'/right-manage',
        children:[
            {
                title:'角色列表',
                path:'/right-manage/role',
                icon:AlignRightOutlined
            },
            {
                title:'权限列表',
                path:'/right-manage/jurisdiction',
                icon:AlignRightOutlined
            }
        ]
    },
    {
        title:'文章管理',
        icon:WalletOutlined,
        path:'/article-manage',
        children:[
            {
                title:'文章列表',
                path:'/article-manage/ArticleList',
                icon:AlignRightOutlined
            },
            {
                title:'文章分类',
                path:'/article-manages/classify',
                icon:AlignRightOutlined
            }
        ]
    }
]
export default menu